"""Initial migration - User model

Revision ID: 6a400ce25111
Revises: 
Create Date: 2026-01-07 04:47:38.655954+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a400ce25111'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='사용자 고유 ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일 (로그인 ID)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='사용자명'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='해싱된 비밀번호'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='전체 이름'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='계정 활성화 상태'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='관리자 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
